version: 2

jobs:
  build:
    machine: true
    working_directory: ~/repo
    steps:
      - checkout
      - run: |
          TAG=0.1.$CIRCLE_BUILD_NUM
          docker build -t cboard/cboard-letsencrypt:$TAG -t cboard/cboard-letsencrypt:latest .
          docker login -u $DOCKER_USER -p $DOCKER_PASS
          docker push cboard/cboard-letsencrypt:latest
          docker push cboard/cboard-letsencrypt:$TAG

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build

